// Generated by CoffeeScript 1.7.1
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
    __hasProp = {}.hasOwnProperty;

  $(function() {
    var disable_category, hide_nav_to_results, page_turner, show_page;
    show_page = function(p) {
      $('section').hide().filter(p).show();
      $('body').toggleClass('splash', p === '#splash');
      return window.scrollTo(0, 0);
    };
    page_turner = function(p) {
      return function() {
        return show_page(p);
      };
    };
    page.base('/');
    page('about', page_turner('#about'));
    page('qna', page_turner('#qna'));
    page('categories', page_turner('#categories'));
    page('agendas', function(context) {
      var c, cid, showall;
      cid = context.hash;
      c = _.find(categories, function(c) {
        return cid === JSON.stringify(c.id);
      });
      c || (c = {
        'category': 'כל האג\'נדות',
        'id': [],
        'fonticon': ''
      });
      showall = !c.id.length;
      $('#agendas h2').empty().text(c.category).prepend($("<i class=\"fa " + (c.fonticon || '') + "\"></i>"));
      $('#agendas-list li').each(function() {
        var a, aid, _ref;
        a = $(this);
        aid = a.attr('id').slice('agenda-'.length);
        return a.toggle(showall || (_ref = parseInt(aid, 10), __indexOf.call(c.id, _ref) >= 0));
      });
      return show_page('#agendas');
    });
    page('results', function() {
      var final;
      final = {};

      /*???
      		$ '#parties-list>li'
      		.each ->
      			$ @
      			.data 'scored',null
       */
      $('#agendas-list>li').each(function() {
        var a, dis_agree, party, ps, score, _results;
        a = $(this);
        if (a.children('button.selected:not(.indifferent)').length !== 0) {
          dis_agree = (function() {
            switch (false) {
              case a.children('button.selected.agree').length === 0:
                return 1.0;
              default:
                return -1.0;
            }
          })();
          console.log('vote for', a.attr('id'), dis_agree);
          ps = $.parseJSON(a.attr('data-parties-scores'));
          console.log('ps', ps);
          _results = [];
          for (party in ps) {
            if (!__hasProp.call(ps, party)) continue;
            score = ps[party];
            _results.push((function(party, score) {

              /*???
              						final[party]=[score]
              						console.log 'p,s',party,score,'pushed to',final
               */
              final[party] || (final[party] = []);
              return final[party].push(score * dis_agree);

              /*???
              						s=$ "#party-#{p}"
              						.data 'scored'
               */
            })(party, score));
          }
          return _results;
        }
      });
      console.log(final);
      $('#parties-list img').hide().first().show();
      return show_page('#results');
    });
    page('', function() {
      return show_page('#splash');
    });
    page.start();
    hide_nav_to_results = function() {
      return $('#agendas footer,#categories footer').toggle($('#agendas button.selected:not(.indifferent)').length !== 0);
    };
    disable_category = function() {
      var cid, voted;
      voted = $('#agendas button.selected:visible:not(.indifferent)').length;
      cid = location.pathname + location.hash;
      return $('#categories a[href="' + cid + '"]').toggleClass('has-votes', voted !== 0);
    };
    $('#agendas-list').on('click', 'button', function(ev) {
      var b, v;
      b = $(ev.target);
      v = (function() {
        switch (false) {
          case !b.hasClass('agree'):
            return 1;
          case !b.hasClass('indifferent'):
            return 0;
          case !b.hasClass('disagree'):
            return -1;
        }
      })();
      console.log('Voted', v, 'on', b.parent().attr('id'));
      b.addClass('selected').siblings().removeClass('selected');
      disable_category();
      return hide_nav_to_results();
    });
    $('#cancel').click(function(ev) {
      $('#agendas button.selected:visible:not(.indifferent)').each(function() {
        return $(this).removeClass('selected').siblings('.indifferent').addClass('selected');
      });
      disable_category();
      return hide_nav_to_results();
    });
    $('.synopsis a').click(function(ev) {
      ev.preventDefault();
      return $(this).parents('#agendas-list>li').children('h4,p:not(.synopsis)').toggle();
    });

    /*??? # Reset all voting buttons to "indifferent". #??? No, load states from URL, so can bookmark/share voting prefs!
    	$ '#agendas-list button'
    	.removeClass 'selected'
    	.filter '.indifferent'
    	.addClass 'selected'
     */
    return hide_nav_to_results();

    /*??? Convert JSON to HTML...
    	_.each parties_scores,(a)->
    		 * absolute_url":"/agenda/113/","parties
    		aid='agenda-'+a.absolute_url.slice '/agenda/'.length,-1
    		ps={}
    		_.each a.parties,(p)->
    			 * {"volume":0.0,"absolute_url":"/party/6/","score":0.0,"name":"6\u05e7\u05d3\u05d9\u05de\u05d4"}
    			if p.score > 0
    				pid=p.absolute_url.slice '/party/'.length,-1
    				 *??? pid='party-'+p.absolute_url.slice '/party/'.length,-1
    				ps[pid]=p.score
    		$ '#'+aid
    		.attr 'data-parties-scores',JSON.stringify ps
     */
  });

}).call(this);
